### PR TITLE
fixed issue220-Impact subpages-Back arrow link

### LINKED ISSUE #220: Impact Subpages: Back Arrow and Blue Link Update
Lets see what the white bar at the top looks like at the same size of the nav bar and decrease
"< Impact Stories" blue link to size 14 font, and use PLEX arrow.  See attached...

screen shot 2019-01-28 at 9 48 39 am

### PR DESCRIPTION
**Pull request by sstrubberg**
Closes #220 

Added PlexArrowLeft and removed ArrowLeft24
Adjusted padding and removed margin

### CODE REVIEW

**Comment by RyanCaruthers** [comment]
@sstrubberg Looks great man!! All good on my end

File: src/components/Markdown/Markdown.js [hunk 1]
```diff
@@ -19,6 +19,7 @@ export class p extends React.Component {
       'page-p--lg': size === 'lg',
       'page-p--xl': size === 'xl',
       'bx--type-expressive-paragraph-01': size === 'xl',
+      'page-p--sm-back': size === 'sm-back',
```
Comment (alisonjoseph) [inline src/components/Markdown/Markdown.js]: would get rid of this and handle it in `<Back>` component

**Comment by alisonjoseph** [comment]
We can merge this in and re-factor later also if needed
